export const CLUB_TYPES = ["PADDLING", "TENNIS", "GOLF", "RUNNING", "ATHLETICS", "HORSE RIDING"];
export const ACCESS = ["FULL", "READ"];
export const FEE_TYPES = { USER_REGISTRATION: "USER_REGISTRATION" }