name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      DOMAIN: ${{ vars.DOMAIN }}
      REGION: ${{ vars.REGION }}
      ACCOUNT: ${{ vars.ACCOUNT }}
      MEMBER_CERT_ARN: ${{ vars.MEMBER_CERT_ARN}}
      ADMIN_CERT_ARN: ${{ vars.ADMIN_CERT_ARN }}
      SNAPSCAN_CERT_ARN: ${{ vars.SNAPSCAN_CERT_ARN }}
      INTERNAL_INFRA_CERT_ARN: ${{ vars.INTERNAL_INFRA_CERT_ARN }}
      ADMIN_FEATURES_CERT_ARN: ${{ vars.ADMIN_FEATURES_CERT_ARN }}
      EMAIL_SENDING_LIMIT: ${{ vars.EMAIL_SENDING_LIMIT }}
      ALLOWED_ORIGIN: ${{ vars.ALLOWED_ORIGIN }}
      MERCHANT_ID: ${{ secrets.MERCHANT_ID }}
      MERCHANT_KEY: ${{ secrets.MERCHANT_KEY }}
      ASSETS_CERT_ARN: ${{ vars.ASSETS_CERT_ARN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create Lambda layers
        run: npm run create-layers
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: CDK Deploy
        run: npm run deploy